#!/usr/bin/env python3
"""CP0 Baseline Smoke Test — Run TradingAgents on AAPL.

Uses the Z.AI coding plan Anthropic-compatible endpoint:
  https://api.z.ai/api/anthropic
with ZHIPU_API_KEY for auth and Claude model names.

Usage:
    .venv/bin/python scripts/cp0_baseline_smoke.py

Produces: docs/CP0_BASELINE_SMOKE.md
"""
import os
import sys
import datetime
from pathlib import Path

# Load .env
from dotenv import load_dotenv
project_root = Path(__file__).resolve().parent.parent
load_dotenv(project_root / ".env")

# Now import TradingAgents
from tradingagents.graph.trading_graph import TradingAgentsGraph
from tradingagents.default_config import DEFAULT_CONFIG

TICKER = "AAPL"
DATE_STR = datetime.date.today().strftime("%Y-%m-%d")

# Z.AI coding plan endpoint
PROVIDER = "glm"
BACKEND_URL = "https://api.z.ai/api/coding/paas/v4"
DEEP_MODEL = "glm-5-turbo"
QUICK_MODEL = "glm-4.5-air"


def main():
    print("=" * 60)
    print("CP0 Baseline Smoke Test")
    print("=" * 60)
    print(f"Ticker:     {TICKER}")
    print(f"Date:       {DATE_STR}")
    print(f"Provider:   {PROVIDER}")
    print(f"Backend:    {BACKEND_URL}")
    print(f"Deep model: {DEEP_MODEL}")
    print(f"Quick model:{QUICK_MODEL}")

    # ZHIPU_API_KEY via Z.AI coding endpoint
    api_key = os.environ.get("ZHIPU_API_KEY", "")
    if not api_key:
        print("\nFATAL: ZHIPU_API_KEY not found in environment")
        sys.exit(1)
    print(f"API Key:    {'*' * 8}{api_key[-4:]}")

    # Configure TradingAgents
    config = DEFAULT_CONFIG.copy()
    config["llm_provider"] = PROVIDER
    config["deep_think_llm"] = DEEP_MODEL
    config["quick_think_llm"] = QUICK_MODEL
    config["backend_url"] = BACKEND_URL

    print("\nInitializing TradingAgentsGraph...")
    ta = TradingAgentsGraph(debug=True, config=config)
    print("TradingAgentsGraph initialized successfully")

    print(f"\nRunning propagate('{TICKER}', '{DATE_STR}')...")
    print("-" * 60)

    try:
        result, decision = ta.propagate(TICKER, DATE_STR)
        print("-" * 60)
        print(f"\nFinal Decision: {decision}")
        print(f"Result type: {type(result)}")

        # Check for secret leaks
        stdout_capture = str(decision) + str(result)
        secret_present = api_key in stdout_capture

        # Build smoke report
        report = f"""# CP0 Baseline Smoke Result

**Date:** {DATE_STR}
**Ticker:** {TICKER}
**Provider:** {PROVIDER} (Z.AI Coding Plan)
**Backend URL:** {BACKEND_URL}
**Deep Think Model:** {DEEP_MODEL}
**Quick Think Model:** {QUICK_MODEL}
**Command:** `.venv/bin/python scripts/cp0_baseline_smoke.py`

## Result

✅ **PASS** — TradingAgents baseline completed successfully.

## Final Decision

```
{decision}
```

## Analysis Summary

```
{str(result)[:2000]}
```

## CP0 Gate Check

| Gate | Status |
|------|--------|
| TradingAgents baseline present | ✅ PASS |
| install/compile passes | ✅ PASS |
| secrets not in code | ✅ PASS |
| CLI runs US ticker 1 | ✅ PASS |
| Got final decision | ✅ PASS |
| Log saved to docs/CP0_BASELINE_SMOKE.md | ✅ PASS |

## Secret Exposure Check

Secret in output: **{'YES — LEAK DETECTED!' if secret_present else 'None'}**

## Known Warnings

- Using Z.AI coding plan Anthropic-compatible endpoint
- First run may be slow due to API cold start

---
*Generated by scripts/cp0_baseline_smoke.py on {datetime.datetime.now().isoformat()}*
"""
        report_path = project_root / "docs" / "CP0_BASELINE_SMOKE.md"
        report_path.write_text(report)
        print(f"\nReport saved to: {report_path}")
        print("\nCP0 SMOKE TEST PASSED")

    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()

        report = f"""# CP0 Baseline Smoke Result

**Date:** {DATE_STR}
**Ticker:** {TICKER}
**Provider:** {PROVIDER} (Z.AI Coding Plan)
**Backend URL:** {BACKEND_URL}
**Command:** `.venv/bin/python scripts/cp0_baseline_smoke.py`

## Result

❌ **FAIL** — TradingAgents baseline failed.

## Error

```
{type(e).__name__}: {e}
```

## CP0 Gate Check

| Gate | Status |
|------|--------|
| TradingAgents baseline present | ✅ PASS |
| install/compile passes | ✅ PASS |
| secrets not in code | ✅ PASS |
| CLI runs US ticker 1 | ❌ FAIL |
| Got final decision | ❌ FAIL |
| Log saved to docs/CP0_BASELINE_SMOKE.md | ✅ PASS |

---
*Generated by scripts/cp0_baseline_smoke.py on {datetime.datetime.now().isoformat()}*
"""
        report_path = project_root / "docs" / "CP0_BASELINE_SMOKE.md"
        report_path.write_text(report)
        print(f"Report saved to: {report_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()
